#!/bin/bash

adb uninstall --user 0 com.android.chrome
adb uninstall --user 0 com.facebook.appmanager
adb uninstall --user 0 com.facebook.services
adb uninstall --user 0 com.facebook.system
adb uninstall --user 0 com.google.android.adservices.ap
adb uninstall --user 0 com.google.android.apps.photos
adb uninstall --user 0 com.google.android.apps.restore
adb uninstall --user 0 com.google.android.apps.youtube.music
adb uninstall --user 0 com.google.android.googlequicksearchbox
adb uninstall --user 0 com.google.android.projection.gearhead
adb uninstall --user 0 com.google.android.youtube
adb uninstall --user 0 com.google.chrome
adb uninstall --user 0 com.google.chrome
adb uninstall --user 0 com.google.mainline.adservices
adb uninstall --user 0 com.microsoft.skydrive
adb uninstall --user 0 com.mygalaxy
adb uninstall --user 0 com.netflix.mediaclient
adb uninstall --user 0 com.netflix.partner.actication
adb uninstall --user 0 com.netflix.partner.activation
adb uninstall --user 0 com.samsung.android.app.spage
adb uninstall --user 0 com.samsung.android.aremoji
adb uninstall --user 0 com.samsung.android.arzone
adb uninstall --user 0 com.samsung.android.game.gamehome
adb uninstall --user 0 com.samsung.android.game.gametools
adb uninstall --user 0 com.samsung.android.game.gos
adb uninstall --user 0 com.samsung.android.spaymini
adb uninstall --user 0 com.sec.android.app.fm
adb uninstall --user 0 com.sec.android.app.samsungapps
adb uninstall --user 0 com.google.android.apps.messaging
adb uninstall --user 0 com.google.android.apps.messaging
adb uninstall --user 0 com.sec.spp.push
adb uninstall --user 0 com.samsung.android.ardrawing
adb uninstall --user 0 com.samsung.android.visionintelligence
abd uninstall --user 0 com.facebook.katana
